name: CD
on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          local-dir: ./
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_MDP }}
          server-dir: www/
          exclude: |
            **/.git*
            **/.git*/**
            **/vendor/**
