name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v3
      with:
        version: 9.6.1
        php_version: '8.2'
        php_extensions: gd mbstring pcov tokenizer
    #- uses: irongut/CodeCoverageSummary@v1.3.0
     # with:
      #  filename: coverage/cobertura-coverage.xml
       # badge: true
        #fail_below_min: true
       # format: markdown
        #hide_branch_rate: false
       # hide_complexity: true
        #indicators: true
       # output: both
        #thresholds: '60 80'
   # - run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
   # - uses: php-actions/phpcs@v1
    #  continue-on-error: true
     # with:
      #  php_version: 8.2
       # path: lib/
        #standard: PSR1
    #- uses: php-actions/phpmd@v1
     # continue-on-error: true
     # with:
      #    php_version: 8.2
      #    path: lib/
      #    output: text
       #   ruleset: ruleset.xml
   # - uses: php-actions/phpstan@v3
    #  continue-on-error: true
    #  with:
     #   command: analyse
      #  path: lib/
    - uses:  SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        local-dir: ./
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_MDP }}
        server-dir: www/
        exclude: |
          **/.git*
          **/.git*/**
          **/vendor/**
  
