name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v3
      with:
        version: 9.6.1
        php_version: '8.2'
        php_extensions: gd mbstring pcov tokenizer

    - uses: irongut/CodeCoverageSummary@v1.3.0
      id: coverage-summary
      with:
        filename: coverage/cobertura-coverage.xml
    - run: echo ${{ steps.coverage-summary.outputs.summary }} >> $GITHUB_STEP_SUMMARY
