name: CI

on: [push]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3