name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v3
      with:
        version: 9.6.1
        php_version: '8.2'
        php_extensions: gd mbstring pcov tokenizer
    - run : cat log/coverage.txt
    - run : echo ‘### Hello world! 🚀’ >> $GITHUB_STEP_SUMMARY
    - uses: irongut/CodeCoverageSummary@v1.3.0
      id: coverage_summary
      with:
        filename: coverage/cobertura-coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - run: echo "$COVERAGE_SUMMARY" >> $GITHUB_STEP_SUMMARY
      env:
          COVERAGE_SUMMARY: ${{ steps.coverage_summary.outputs.summary }}
